### ISSUE TITLE
Last run test not in coverage

### ISSUE THREAD

**Issue by ghost** [ugocastro/demo-xcode7-coverage#2]
Hi, when running UI Tests it appears that the last test (testSum) is never included in coverage report.
When I add a empty test called testZZZ, it's OK. Is this a known regression in Xcode or maybe something else? Thanks!

**Comment by ugocastro** [comment]
Hi @VladislavJevremovic , thanks for reporting it. I noticed this behavior before and I believe that's a bug on **Coverage** in _Xcode_. I executed the tests more than once and sometimes it returns 69% of coverage (do not cover `sum` method) on `ViewController` class and others 81% (do cover `sum` method) as images below shows:

![captura de tela 2015-12-02 as 12 54 26](https://cloud.githubusercontent.com/assets/2566278/11535808/4712a91a-98f4-11e5-8089-ef5601d3be6b.png)
<p>![captura de tela 2015-12-02 as 12 55 09](https://cloud.githubusercontent.com/assets/2566278/11535809/472d648a-98f4-11e5-9735-ce037fd49d31.png)

 Try executing the tests more than once and tell me if the coverage increases or not.

Best wishes,

Ugo Castro.

**Comment by ghost** [comment]
Hello again, thanks for replying quickly! I did run them several times, but coverage is stuck at 80%:

<img width="756" alt="2" src="https://cloud.githubusercontent.com/assets/7195536/11539578/1364aa76-9928-11e5-949d-25435c246af0.png">

However, currently Xcode runs tests in alphabetical order:

<img width="757" alt="1" src="https://cloud.githubusercontent.com/assets/7195536/11539596/2eaf27a2-9928-11e5-87ed-0aea9bd2810d.png">

So I wanted to confirm there must be a bug in that coverage will **not** take into account the last test (alphabetically). I tried with a dummy one:

<img width="761" alt="3" src="https://cloud.githubusercontent.com/assets/7195536/11539637/74c9307a-9928-11e5-9602-3a3a40be5137.png">

Now after running there's a bump in coverage and sum() is there alright:

<img width="759" alt="5" src="https://cloud.githubusercontent.com/assets/7195536/11539661/90743694-9928-11e5-9faa-2c80fc3eb8a8.png">

The order is still alphabetical:

<img width="758" alt="4" src="https://cloud.githubusercontent.com/assets/7195536/11539645/80731aa8-9928-11e5-8c9a-dca06d271971.png">

This might be a workaround for the time being (until and if it gets fixed).
(You may close the issue as it's not actually your fault)

By the way, thanks for posting this example, it really helped me out today ;)

**Comment by ugocastro** [comment]
You're welcome! Feel free to fork the repo and work on a fix for this problem if you discover something. I am happy to have helped you. Let me know if you need something, all right? See ya!
